// src/OpenCode.AngularFrontend/src/shared/components/admin-table/admin-table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { PaginationComponent } from '../pagination/pagination';

export interface AdminColumn {
  key: string;
  label: string;
  sortable?: boolean;
  render?: (item: any) => string;
}

@Component({
  selector: 'app-admin-table',
  standalone: true,
  imports: [FormsModule, PaginationComponent],
  templateUrl: './admin-table.component.html',
  styleUrl: './admin-table.component.css',
})
export class AdminTableComponent {
  @Input() columns: AdminColumn[] = [];
  @Input() data: any[] = [];
  @Input() keyExtractor: (item: any) => string | number = () => 0;
  @Input() isLoading = false;
  @Input() page = 1;
  @Input() totalPages = 1;
  @Input() totalCount = 0;
  @Output() edit = new EventEmitter<any>();
  @Output() delete = new EventEmitter<any>();
  @Output() pageChange = new EventEmitter<number>();

  search = '';
  sortKey: string | null = null;
  sortDir: 'asc' | 'desc' = 'asc';

  get filteredData(): any[] {
    if (!this.search) return this.data;
    const q = this.search.toLowerCase();
    return this.data.filter((item: any) =>
      this.columns.some(col => {
        const val = item[col.key];
        return val != null && String(val).toLowerCase().includes(q);
      })
    );
  }

  get sortedData(): any[] {
    if (!this.sortKey) return this.filteredData;
    return [...this.filteredData].sort((a: any, b: any) => {
      const aVal = a[this.sortKey!];
      const bVal = b[this.sortKey!];
      if (aVal == null) return 1;
      if (bVal == null) return -1;
      const cmp = String(aVal).localeCompare(String(bVal));
      return this.sortDir === 'asc' ? cmp : -cmp;
    });
  }

  toggleSort(key: string): void {
    if (this.sortKey === key) {
      this.sortDir = this.sortDir === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortKey = key;
      this.sortDir = 'asc';
    }
  }
}

@if (isLoading) {
  <div class="p-8 text-center text-gray-400">Loading...</div>
} @else {
  <div class="mb-4">
    <input type="text" [(ngModel)]="search" placeholder="Search..."
      class="w-full p-2 border rounded text-sm" />
  </div>
  <table class="w-full border-collapse">
    <thead>
      <tr class="bg-gray-100 text-left">
        @for (col of columns; track col.key) {
          <th class="p-3 border-b-2 border-gray-300 text-sm font-semibold"
            [class.cursor-pointer]="col.sortable"
            [class.hover:bg-gray-200]="col.sortable"
            (click)="col.sortable && toggleSort(col.key)">
            {{ col.label }}
            @if (sortKey === col.key) {
              <span>{{ sortDir === 'asc' ? ' ▲' : ' ▼' }}</span>
            }
          </th>
        }
        <th class="p-3 border-b-2 border-gray-300 text-sm font-semibold">Actions</th>
      </tr>
    </thead>
    <tbody>
      @for (item of sortedData; track keyExtractor(item)) {
        <tr class="border-b border-gray-200 hover:bg-gray-50">
          @for (col of columns; track col.key) {
            <td class="p-2.5 px-3 text-sm">
              {{ col.render ? col.render(item) : item[col.key] ?? '' }}
            </td>
          }
          <td class="p-2.5 px-3">
            <div class="flex gap-2">
              <button (click)="edit.emit(item)"
                class="px-3 py-1 bg-blue-500 text-white rounded text-sm hover:bg-blue-600">
                Edit
              </button>
              <button (click)="delete.emit(item)"
                class="px-3 py-1 bg-red-500 text-white rounded text-sm hover:bg-red-600">
                Delete
              </button>
            </div>
          </td>
        </tr>
      }
    </tbody>
  </table>
  <div class="mt-4">
    <app-pagination [page]="page" [totalPages]="totalPages" (pageChange)="pageChange.emit($event)"></app-pagination>
  </div>
}

// src/OpenCode.Frontend/src/components/AdminTable.tsx
import { useState, useMemo, type ReactNode } from 'react'
import Pagination from './Pagination'

interface AdminColumn<T> {
  key: string
  label: string
  sortable?: boolean
  render?: (item: T) => ReactNode
}

interface AdminTableProps<T> {
  columns: AdminColumn<T>[]
  data: T[]
  keyExtractor: (item: T) => string | number
  onEdit?: (item: T) => void
  onDelete?: (item: T) => void
  isLoading?: boolean
  page: number
  pageSize: number
  totalCount: number
  totalPages: number
  onPageChange: (page: number) => void
}

export default function AdminTable<T extends Record<string, unknown>>({
  columns, data, keyExtractor, onEdit, onDelete,
  isLoading, page, totalPages, onPageChange,
}: AdminTableProps<T>) {
  const [search, setSearch] = useState('')
  const [sortKey, setSortKey] = useState<string | null>(null)
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')

  const filtered = useMemo(() => {
    if (!search) return data
    const q = search.toLowerCase()
    return data.filter(item =>
      columns.some(col => {
        const val = item[col.key]
        return val != null && String(val).toLowerCase().includes(q)
      })
    )
  }, [data, search, columns])

  const sorted = useMemo(() => {
    if (!sortKey) return filtered
    return [...filtered].sort((a, b) => {
      const aVal = a[sortKey]; const bVal = b[sortKey]
      if (aVal == null) return 1; if (bVal == null) return -1
      const cmp = String(aVal).localeCompare(String(bVal))
      return sortDir === 'asc' ? cmp : -cmp
    })
  }, [filtered, sortKey, sortDir])

  const handleSort = (key: string) => {
    if (sortKey === key) setSortDir(d => d === 'asc' ? 'desc' : 'asc')
    else { setSortKey(key); setSortDir('asc') }
  }

  if (isLoading) return <div className="p-8 text-center">Loading...</div>

  return (
    <div>
      <div className="mb-4">
        <input
          type="text" placeholder="Search..."
          value={search} onChange={e => setSearch(e.target.value)}
          className="w-full p-2 border rounded"
        />
      </div>
      <table className="w-full border-collapse">
        <thead>
          <tr className="bg-gray-100 text-left">
            {columns.map(col => (
              <th key={col.key}
                className={`p-3 border-b-2 border-gray-300 ${col.sortable ? 'cursor-pointer hover:bg-gray-200 select-none' : ''}`}
                onClick={() => col.sortable && handleSort(col.key)}>
                {col.label}
                {sortKey === col.key && (sortDir === 'asc' ? ' ▲' : ' ▼')}
              </th>
            ))}
            {(onEdit || onDelete) && <th className="p-3 border-b-2 border-gray-300">Actions</th>}
          </tr>
        </thead>
        <tbody>
          {sorted.map(item => (
            <tr key={keyExtractor(item)} className="border-b border-gray-200 hover:bg-gray-50">
              {columns.map(col => (
                <td key={col.key} className="p-2.5 px-3">
                  {col.render ? col.render(item) : String(item[col.key] ?? '')}
                </td>
              ))}
              {(onEdit || onDelete) && (
                <td className="p-2.5 px-3">
                  <div className="flex gap-2">
                    {onEdit && (
                      <button onClick={() => onEdit(item)} className="px-3 py-1 bg-blue-500 text-white rounded text-sm hover:bg-blue-600">
                        Edit
                      </button>
                    )}
                    {onDelete && (
                      <button onClick={() => onDelete(item)} className="px-3 py-1 bg-red-500 text-white rounded text-sm hover:bg-red-600">
                        Delete
                      </button>
                    )}
                  </div>
                </td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
      <div className="mt-4">
        <Pagination page={page} totalPages={totalPages} onPageChange={onPageChange} />
      </div>
    </div>
  )
}
