// src/OpenCode.AngularFrontend/src/shared/components/confirm-dialog/confirm-dialog.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-confirm-dialog',
  standalone: true,
  imports: [],
  templateUrl: './confirm-dialog.component.html',
  styleUrl: './confirm-dialog.component.css',
})
export class ConfirmDialogComponent {
  @Input() isOpen = false;
  @Input() title = '';
  @Input() message = '';
  @Input() entityName = '';
  @Input() entityType = '';
  @Input() isLoading = false;
  @Output() confirm = new EventEmitter<void>();
  @Output() cancel = new EventEmitter<void>();
}

@if (isOpen) {
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
    <div class="bg-white rounded-lg shadow-xl p-6 max-w-md w-full">
      <h3 class="text-lg font-bold text-red-600 mb-2">{{ title }}</h3>
      <p class="text-gray-600 mb-4">{{ message }}</p>
      <div class="bg-gray-50 rounded p-3 mb-4">
        <p><strong>Type:</strong> {{ entityType }}</p>
        <p><strong>Name:</strong> {{ entityName }}</p>
      </div>
      <div class="flex justify-end gap-3">
        <button (click)="cancel.emit()" [disabled]="isLoading"
          class="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300">
          Cancel
        </button>
        <button (click)="confirm.emit()" [disabled]="isLoading"
          class="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 disabled:opacity-50">
          {{ isLoading ? 'Deleting...' : 'Delete' }}
        </button>
      </div>
    </div>
  </div>
}

// src/OpenCode.Frontend/src/components/ConfirmDialog.tsx
interface ConfirmDialogProps {
  isOpen: boolean
  title: string
  message: string
  entityName: string
  entityType: string
  onConfirm: () => void
  onCancel: () => void
  isLoading?: boolean
}

export default function ConfirmDialog({
  isOpen, title, message, entityName, entityType,
  onConfirm, onCancel, isLoading,
}: ConfirmDialogProps) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-white rounded-lg shadow-xl p-6 max-w-md w-full">
        <h3 className="text-lg font-bold text-red-600 mb-2">{title}</h3>
        <p className="text-gray-600 mb-4">{message}</p>
        <div className="bg-gray-50 rounded p-3 mb-4">
          <p><strong>Type:</strong> {entityType}</p>
          <p><strong>Name:</strong> {entityName}</p>
        </div>
        <div className="flex justify-end gap-3">
          <button onClick={onCancel} disabled={isLoading}
            className="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300">
            Cancel
          </button>
          <button onClick={onConfirm} disabled={isLoading}
            className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 disabled:opacity-50">
            {isLoading ? 'Deleting...' : 'Delete'}
          </button>
        </div>
      </div>
    </div>
  )
}
